# Generated by Django 5.2.3 on 2025-06-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
            ],
        ),
    ]
