# Generated by Django 5.2.3 on 2025-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_lectureschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
